### ISSUE TITLE
add a gitignore file

### ISSUE THREAD

**Issue by martcpp** [nafisalawalidris/FastAPI-learning#1]
please add a a **.gitignore** file so you don't push unwanted code to GitHub [read here about it](https://www.designveloper.com/blog/how-gitignore-works/l)

**Comment by nafisalawalidris** [comment]
I have added a `.gitignore` file to the repository to ensure that unwanted files and directories are not pushed to GitHub. The file includes common patterns for ignoring Python bytecode and virtual environment directories. Please check the `.gitignore` file in the repository and let me know if there are any additional patterns or files you think should be included.
