### ISSUE TITLE
add a requirement.txt file so it easy for other to know the package you use

### ISSUE THREAD

**Issue by martcpp** [nafisalawalidris/FastAPI-learning#2]

**Comment by martcpp** [comment]
read more about it here [What is requirements.txt and why is it important for Python](https://medium.com/@agusmahari/what-is-requirements-txt-and-why-is-it-important-for-python-a4535523e2e9)

**Comment by nafisalawalidris** [comment]
I have added a `requirements.txt` file to the repository with the specific package versions used in the `main.py`. This should help with managing dependencies and setting up the environment. Here are the packages included:
- FastAPI==0.68.1
- Uvicorn==0.15.0
- SQLAlchemy==1.4.27
- Pydantic==1.8.2
Please check the `requirements.txt` file in the repository and let me know if there's anything else you need.
